AllCops:
  Includes:
    - lib/**
    - spec/**
  Excludes:
    - examples/**

# ignore long lines
LineLength:
  Enabled: false

# Allow small arrays before forcing  %w or %W
WordArray:
  MinSize: 3

# Ignore this for now
MethodLength:
  Max: 125
